const CONSTITUENCY_DATA = {
  "Andhra Pradesh": [
    {
      "name": "Visakhapatnam",
      "mp": "M. Sribharat",
      "party": "TDP",
      "voteShare": 50.9,
      "voteShare2019": 53.4,
      "runnerParty": "YSRCP",
      "runnerVoteShare": 36.7,
      "electorate": 2337533,
      "turnout": 78.8,
      "category": "General"
    },
    {
      "name": "Vijayawada",
      "mp": "Kesineni Sivanath",
      "party": "TDP",
      "voteShare": 56.6,
      "voteShare2019": 54.1,
      "runnerParty": "YSRCP",
      "runnerVoteShare": 46.4,
      "electorate": 1889820,
      "turnout": 57.7,
      "category": "General"
    },
    {
      "name": "Guntur",
      "mp": "Chandra Sekhar Pemmasani",
      "party": "TDP",
      "voteShare": 58.5,
      "voteShare2019": 59.9,
      "runnerParty": "YSRCP",
      "runnerVoteShare": 25.6,
      "electorate": 2224335,
      "turnout": 50.0,
      "category": "General"
    },
    {
      "name": "Tirupati",
      "mp": "M. Gurumoorthy",
      "party": "YSRCP",
      "voteShare": 50.8,
      "voteShare2019": 53.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 20.8,
      "electorate": 2268085,
      "turnout": 61.1,
      "category": "SC"
    },
    {
      "name": "Kadapa",
      "mp": "Y. S. Avinash Reddy",
      "party": "YSRCP",
      "voteShare": 59.0,
      "voteShare2019": 62.6,
      "runnerParty": "INC",
      "runnerVoteShare": 51.5,
      "electorate": 2105910,
      "turnout": 62.6,
      "category": "General"
    }
  ],
  "Arunachal Pradesh": [
    {
      "name": "Arunachal West",
      "mp": "Kiren Rijiju",
      "party": "BJP",
      "voteShare": 51.3,
      "voteShare2019": 46.3,
      "runnerParty": "INC",
      "runnerVoteShare": 26.9,
      "electorate": 1612892,
      "turnout": 50.9,
      "category": "General"
    },
    {
      "name": "Arunachal East",
      "mp": "Tapir Gao",
      "party": "BJP",
      "voteShare": 56.8,
      "voteShare2019": 52.8,
      "runnerParty": "INC",
      "runnerVoteShare": 25.3,
      "electorate": 1997568,
      "turnout": 73.2,
      "category": "General"
    },
    {
      "name": "Tawang",
      "mp": "Pema Khandu",
      "party": "BJP",
      "voteShare": 58.0,
      "voteShare2019": 58.5,
      "runnerParty": "INC",
      "runnerVoteShare": 44.8,
      "electorate": 1913853,
      "turnout": 50.7,
      "category": "General"
    },
    {
      "name": "Pasighat",
      "mp": "Ninong Ering",
      "party": "BJP",
      "voteShare": 52.8,
      "voteShare2019": 54.7,
      "runnerParty": "INC",
      "runnerVoteShare": 45.2,
      "electorate": 1740360,
      "turnout": 75.4,
      "category": "General"
    },
    {
      "name": "Itanagar",
      "mp": "Techi Kaso",
      "party": "BJP",
      "voteShare": 40.8,
      "voteShare2019": 44.4,
      "runnerParty": "INC",
      "runnerVoteShare": 20.5,
      "electorate": 2399793,
      "turnout": 62.2,
      "category": "General"
    }
  ],
  "Assam": [
    {
      "name": "Dhubri",
      "mp": "Rakibul Hussain",
      "party": "INC",
      "voteShare": 54.1,
      "voteShare2019": 52.5,
      "runnerParty": "AIUDF",
      "runnerVoteShare": 33.3,
      "electorate": 1508155,
      "turnout": 58.5,
      "category": "General"
    },
    {
      "name": "Guwahati",
      "mp": "Bijuli Kalita Medhi",
      "party": "BJP",
      "voteShare": 46.3,
      "voteShare2019": 43.1,
      "runnerParty": "INC",
      "runnerVoteShare": 33.4,
      "electorate": 2295280,
      "turnout": 55.2,
      "category": "General"
    },
    {
      "name": "Dibrugarh",
      "mp": "Sarbananda Sonowal",
      "party": "BJP",
      "voteShare": 55.2,
      "voteShare2019": 56.1,
      "runnerParty": "AJP",
      "runnerVoteShare": 34.2,
      "electorate": 1825803,
      "turnout": 75.4,
      "category": "General"
    },
    {
      "name": "Jorhat",
      "mp": "Gaurav Gogoi",
      "party": "INC",
      "voteShare": 45.3,
      "voteShare2019": 41.5,
      "runnerParty": "BJP",
      "runnerVoteShare": 20.7,
      "electorate": 1773919,
      "turnout": 57.9,
      "category": "General"
    },
    {
      "name": "Silchar",
      "mp": "Parimal Suklabaidya",
      "party": "BJP",
      "voteShare": 56.2,
      "voteShare2019": 58.8,
      "runnerParty": "INC",
      "runnerVoteShare": 33.3,
      "electorate": 2122947,
      "turnout": 51.5,
      "category": "SC"
    }
  ],
  "Bihar": [
    {
      "name": "Patna Sahib",
      "mp": "Ravi Shankar Prasad",
      "party": "BJP",
      "voteShare": 45.3,
      "voteShare2019": 47.9,
      "runnerParty": "INC",
      "runnerVoteShare": 39.8,
      "electorate": 1787272,
      "turnout": 51.5,
      "category": "General"
    },
    {
      "name": "Hajipur",
      "mp": "Chirag Paswan",
      "party": "LJP",
      "voteShare": 46.2,
      "voteShare2019": 48.5,
      "runnerParty": "RJD",
      "runnerVoteShare": 25.8,
      "electorate": 2420978,
      "turnout": 51.8,
      "category": "SC"
    },
    {
      "name": "Saran",
      "mp": "Rajiv Pratap Rudy",
      "party": "BJP",
      "voteShare": 53.4,
      "voteShare2019": 53.6,
      "runnerParty": "RJD",
      "runnerVoteShare": 32.9,
      "electorate": 1691528,
      "turnout": 75.4,
      "category": "General"
    },
    {
      "name": "Begusarai",
      "mp": "Giriraj Singh",
      "party": "BJP",
      "voteShare": 46.2,
      "voteShare2019": 42.1,
      "runnerParty": "CPI",
      "runnerVoteShare": 24.6,
      "electorate": 2451702,
      "turnout": 74.0,
      "category": "General"
    },
    {
      "name": "Purnia",
      "mp": "Pappu Yadav",
      "party": "IND",
      "voteShare": 55.9,
      "voteShare2019": 52.2,
      "runnerParty": "JD(U)",
      "runnerVoteShare": 39.6,
      "electorate": 2333969,
      "turnout": 69.1,
      "category": "General"
    }
  ],
  "Chhattisgarh": [
    {
      "name": "Raipur",
      "mp": "Brijmohan Agrawal",
      "party": "BJP",
      "voteShare": 40.2,
      "voteShare2019": 38.1,
      "runnerParty": "INC",
      "runnerVoteShare": 30.0,
      "electorate": 1683931,
      "turnout": 78.5,
      "category": "General"
    },
    {
      "name": "Rajnandgaon",
      "mp": "Santosh Pandey",
      "party": "BJP",
      "voteShare": 50.8,
      "voteShare2019": 53.0,
      "runnerParty": "INC",
      "runnerVoteShare": 44.7,
      "electorate": 1879982,
      "turnout": 62.2,
      "category": "General"
    },
    {
      "name": "Korba",
      "mp": "Jyotsna Mahant",
      "party": "INC",
      "voteShare": 58.1,
      "voteShare2019": 57.2,
      "runnerParty": "BJP",
      "runnerVoteShare": 36.3,
      "electorate": 1586118,
      "turnout": 65.4,
      "category": "General"
    },
    {
      "name": "Bilaspur",
      "mp": "Tokhan Sahu",
      "party": "BJP",
      "voteShare": 43.7,
      "voteShare2019": 45.6,
      "runnerParty": "INC",
      "runnerVoteShare": 27.3,
      "electorate": 2235066,
      "turnout": 79.0,
      "category": "General"
    },
    {
      "name": "Bastar",
      "mp": "Mahesh Kashyap",
      "party": "BJP",
      "voteShare": 48.9,
      "voteShare2019": 46.5,
      "runnerParty": "INC",
      "runnerVoteShare": 40.5,
      "electorate": 1954727,
      "turnout": 66.2,
      "category": "ST"
    }
  ],
  "Goa": [
    {
      "name": "North Goa",
      "mp": "Shripad Yesso Naik",
      "party": "BJP",
      "voteShare": 47.0,
      "voteShare2019": 42.3,
      "runnerParty": "INC",
      "runnerVoteShare": 43.6,
      "electorate": 1588575,
      "turnout": 75.3,
      "category": "General"
    },
    {
      "name": "South Goa",
      "mp": "Viriato Fernandes",
      "party": "INC",
      "voteShare": 44.4,
      "voteShare2019": 44.0,
      "runnerParty": "BJP",
      "runnerVoteShare": 28.6,
      "electorate": 2240979,
      "turnout": 65.5,
      "category": "General"
    },
    {
      "name": "Panaji",
      "mp": "Babush Monserrate",
      "party": "BJP",
      "voteShare": 46.5,
      "voteShare2019": 44.2,
      "runnerParty": "INC",
      "runnerVoteShare": 34.1,
      "electorate": 1894663,
      "turnout": 75.2,
      "category": "General"
    },
    {
      "name": "Margao",
      "mp": "Digambar Kamat",
      "party": "BJP",
      "voteShare": 54.7,
      "voteShare2019": 50.5,
      "runnerParty": "INC",
      "runnerVoteShare": 44.9,
      "electorate": 1529430,
      "turnout": 69.3,
      "category": "General"
    },
    {
      "name": "Vasco",
      "mp": "Carlos Almeida",
      "party": "BJP",
      "voteShare": 56.9,
      "voteShare2019": 59.1,
      "runnerParty": "INC",
      "runnerVoteShare": 49.0,
      "electorate": 1610773,
      "turnout": 51.8,
      "category": "General"
    }
  ],
  "Gujarat": [
    {
      "name": "Gandhinagar",
      "mp": "Amit Shah",
      "party": "BJP",
      "voteShare": 49.2,
      "voteShare2019": 49.0,
      "runnerParty": "INC",
      "runnerVoteShare": 24.7,
      "electorate": 2161734,
      "turnout": 66.4,
      "category": "General"
    },
    {
      "name": "Surat",
      "mp": "Mukesh Dalal",
      "party": "BJP",
      "voteShare": 50.9,
      "voteShare2019": 52.6,
      "runnerParty": "INC",
      "runnerVoteShare": 48.6,
      "electorate": 1710650,
      "turnout": 67.3,
      "category": "General"
    },
    {
      "name": "Navsari",
      "mp": "C. R. Patil",
      "party": "BJP",
      "voteShare": 45.4,
      "voteShare2019": 44.2,
      "runnerParty": "INC",
      "runnerVoteShare": 22.6,
      "electorate": 2346542,
      "turnout": 50.1,
      "category": "General"
    },
    {
      "name": "Rajkot",
      "mp": "Parshottam Rupala",
      "party": "BJP",
      "voteShare": 50.7,
      "voteShare2019": 52.5,
      "runnerParty": "INC",
      "runnerVoteShare": 34.2,
      "electorate": 2151580,
      "turnout": 74.4,
      "category": "General"
    },
    {
      "name": "Porbandar",
      "mp": "Mansukh Mandaviya",
      "party": "BJP",
      "voteShare": 57.3,
      "voteShare2019": 58.5,
      "runnerParty": "INC",
      "runnerVoteShare": 53.8,
      "electorate": 2320573,
      "turnout": 70.1,
      "category": "General"
    }
  ],
  "Haryana": [
    {
      "name": "Rohtak",
      "mp": "Deepender Singh Hooda",
      "party": "INC",
      "voteShare": 55.4,
      "voteShare2019": 50.5,
      "runnerParty": "BJP",
      "runnerVoteShare": 40.9,
      "electorate": 1600430,
      "turnout": 58.9,
      "category": "General"
    },
    {
      "name": "Karnal",
      "mp": "Manohar Lal Khattar",
      "party": "BJP",
      "voteShare": 57.3,
      "voteShare2019": 53.0,
      "runnerParty": "INC",
      "runnerVoteShare": 32.2,
      "electorate": 2222439,
      "turnout": 55.0,
      "category": "General"
    },
    {
      "name": "Gurgaon",
      "mp": "Rao Inderjit Singh",
      "party": "BJP",
      "voteShare": 54.0,
      "voteShare2019": 58.9,
      "runnerParty": "INC",
      "runnerVoteShare": 29.5,
      "electorate": 2092689,
      "turnout": 60.8,
      "category": "General"
    },
    {
      "name": "Hisar",
      "mp": "Jai Prakash",
      "party": "INC",
      "voteShare": 44.7,
      "voteShare2019": 46.9,
      "runnerParty": "BJP",
      "runnerVoteShare": 30.9,
      "electorate": 1636227,
      "turnout": 60.3,
      "category": "General"
    },
    {
      "name": "Sirsa",
      "mp": "Selja Kumari",
      "party": "INC",
      "voteShare": 54.2,
      "voteShare2019": 51.9,
      "runnerParty": "BJP",
      "runnerVoteShare": 40.3,
      "electorate": 2163278,
      "turnout": 62.5,
      "category": "SC"
    }
  ],
  "Himachal Pradesh": [
    {
      "name": "Mandi",
      "mp": "Kangana Ranaut",
      "party": "BJP",
      "voteShare": 54.7,
      "voteShare2019": 57.5,
      "runnerParty": "INC",
      "runnerVoteShare": 23.7,
      "electorate": 1854077,
      "turnout": 76.4,
      "category": "General"
    },
    {
      "name": "Hamirpur",
      "mp": "Anurag Thakur",
      "party": "BJP",
      "voteShare": 45.7,
      "voteShare2019": 46.6,
      "runnerParty": "INC",
      "runnerVoteShare": 43.2,
      "electorate": 2340450,
      "turnout": 58.7,
      "category": "General"
    },
    {
      "name": "Shimla",
      "mp": "Suresh Kumar Kashyap",
      "party": "BJP",
      "voteShare": 52.0,
      "voteShare2019": 52.6,
      "runnerParty": "INC",
      "runnerVoteShare": 46.2,
      "electorate": 1775956,
      "turnout": 51.2,
      "category": "SC"
    },
    {
      "name": "Kangra",
      "mp": "Rajeev Bhardwaj",
      "party": "BJP",
      "voteShare": 46.0,
      "voteShare2019": 46.6,
      "runnerParty": "INC",
      "runnerVoteShare": 28.6,
      "electorate": 1619252,
      "turnout": 69.8,
      "category": "General"
    },
    {
      "name": "Kullu",
      "mp": "Govind Singh Thakur",
      "party": "BJP",
      "voteShare": 58.1,
      "voteShare2019": 53.2,
      "runnerParty": "INC",
      "runnerVoteShare": 32.3,
      "electorate": 1817264,
      "turnout": 64.7,
      "category": "General"
    }
  ],
  "Jharkhand": [
    {
      "name": "Ranchi",
      "mp": "Sanjay Seth",
      "party": "BJP",
      "voteShare": 42.9,
      "voteShare2019": 39.6,
      "runnerParty": "INC",
      "runnerVoteShare": 35.6,
      "electorate": 1725341,
      "turnout": 69.8,
      "category": "General"
    },
    {
      "name": "Dumka",
      "mp": "Nalin Soren",
      "party": "JMM",
      "voteShare": 59.2,
      "voteShare2019": 61.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 20.2,
      "electorate": 1746395,
      "turnout": 73.0,
      "category": "ST"
    },
    {
      "name": "Godda",
      "mp": "Nishikant Dubey",
      "party": "BJP",
      "voteShare": 43.2,
      "voteShare2019": 46.0,
      "runnerParty": "INC",
      "runnerVoteShare": 23.5,
      "electorate": 2154188,
      "turnout": 71.0,
      "category": "General"
    },
    {
      "name": "Hazaribagh",
      "mp": "Manish Jaiswal",
      "party": "BJP",
      "voteShare": 59.3,
      "voteShare2019": 61.4,
      "runnerParty": "INC",
      "runnerVoteShare": 43.1,
      "electorate": 2160405,
      "turnout": 65.8,
      "category": "General"
    },
    {
      "name": "Dhanbad",
      "mp": "Dulu Mahato",
      "party": "BJP",
      "voteShare": 43.7,
      "voteShare2019": 43.1,
      "runnerParty": "INC",
      "runnerVoteShare": 31.5,
      "electorate": 2489808,
      "turnout": 52.0,
      "category": "General"
    }
  ],
  "Karnataka": [
    {
      "name": "Bangalore South",
      "mp": "Tejasvi Surya",
      "party": "BJP",
      "voteShare": 59.0,
      "voteShare2019": 63.2,
      "runnerParty": "INC",
      "runnerVoteShare": 25.9,
      "electorate": 2390555,
      "turnout": 67.2,
      "category": "General"
    },
    {
      "name": "Mysore",
      "mp": "Yaduveer Wadiyar",
      "party": "BJP",
      "voteShare": 47.1,
      "voteShare2019": 51.6,
      "runnerParty": "INC",
      "runnerVoteShare": 39.1,
      "electorate": 2410936,
      "turnout": 50.1,
      "category": "General"
    },
    {
      "name": "Mandya",
      "mp": "H. D. Kumaraswamy",
      "party": "JDS",
      "voteShare": 46.7,
      "voteShare2019": 43.5,
      "runnerParty": "INC",
      "runnerVoteShare": 27.7,
      "electorate": 1614072,
      "turnout": 79.9,
      "category": "General"
    },
    {
      "name": "Dharwad",
      "mp": "Pralhad Joshi",
      "party": "BJP",
      "voteShare": 49.4,
      "voteShare2019": 48.2,
      "runnerParty": "INC",
      "runnerVoteShare": 27.8,
      "electorate": 1592799,
      "turnout": 75.5,
      "category": "General"
    },
    {
      "name": "Gulbarga",
      "mp": "Radhakrishna Doddamani",
      "party": "INC",
      "voteShare": 58.1,
      "voteShare2019": 58.2,
      "runnerParty": "BJP",
      "runnerVoteShare": 20.5,
      "electorate": 2151326,
      "turnout": 75.2,
      "category": "SC"
    }
  ],
  "Kerala": [
    {
      "name": "Wayanad",
      "mp": "Rahul Gandhi",
      "party": "INC",
      "voteShare": 54.4,
      "voteShare2019": 58.1,
      "runnerParty": "CPI",
      "runnerVoteShare": 34.5,
      "electorate": 2183017,
      "turnout": 64.5,
      "category": "General"
    },
    {
      "name": "Thiruvananthapuram",
      "mp": "Shashi Tharoor",
      "party": "INC",
      "voteShare": 40.4,
      "voteShare2019": 40.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 38.0,
      "electorate": 2104290,
      "turnout": 68.5,
      "category": "General"
    },
    {
      "name": "Thrissur",
      "mp": "Suresh Gopi",
      "party": "BJP",
      "voteShare": 47.6,
      "voteShare2019": 42.7,
      "runnerParty": "CPI",
      "runnerVoteShare": 44.5,
      "electorate": 2480739,
      "turnout": 70.1,
      "category": "General"
    },
    {
      "name": "Ernakulam",
      "mp": "Hibi Eden",
      "party": "INC",
      "voteShare": 50.4,
      "voteShare2019": 54.4,
      "runnerParty": "CPI(M)",
      "runnerVoteShare": 40.4,
      "electorate": 1895118,
      "turnout": 70.4,
      "category": "General"
    },
    {
      "name": "Kollam",
      "mp": "N. K. Premachandran",
      "party": "RSP",
      "voteShare": 41.8,
      "voteShare2019": 45.3,
      "runnerParty": "CPI(M)",
      "runnerVoteShare": 33.4,
      "electorate": 1583459,
      "turnout": 74.1,
      "category": "General"
    }
  ],
  "Madhya Pradesh": [
    {
      "name": "Indore",
      "mp": "Shankar Lalwani",
      "party": "BJP",
      "voteShare": 41.2,
      "voteShare2019": 46.2,
      "runnerParty": "NOTA",
      "runnerVoteShare": 26.1,
      "electorate": 1574772,
      "turnout": 54.0,
      "category": "General"
    },
    {
      "name": "Vidisha",
      "mp": "Shivraj Singh Chouhan",
      "party": "BJP",
      "voteShare": 44.8,
      "voteShare2019": 42.0,
      "runnerParty": "INC",
      "runnerVoteShare": 31.8,
      "electorate": 2301118,
      "turnout": 62.2,
      "category": "General"
    },
    {
      "name": "Guna",
      "mp": "Jyotiraditya Scindia",
      "party": "BJP",
      "voteShare": 53.8,
      "voteShare2019": 55.9,
      "runnerParty": "INC",
      "runnerVoteShare": 40.1,
      "electorate": 2340124,
      "turnout": 69.0,
      "category": "General"
    },
    {
      "name": "Bhopal",
      "mp": "Alok Sharma",
      "party": "BJP",
      "voteShare": 52.7,
      "voteShare2019": 56.7,
      "runnerParty": "INC",
      "runnerVoteShare": 28.6,
      "electorate": 2449887,
      "turnout": 50.4,
      "category": "General"
    },
    {
      "name": "Chhindwara",
      "mp": "Vivek Sahu",
      "party": "BJP",
      "voteShare": 52.2,
      "voteShare2019": 51.9,
      "runnerParty": "INC",
      "runnerVoteShare": 44.2,
      "electorate": 2230864,
      "turnout": 64.6,
      "category": "General"
    }
  ],
  "Maharashtra": [
    {
      "name": "Mumbai North",
      "mp": "Piyush Goyal",
      "party": "BJP",
      "voteShare": 55.0,
      "voteShare2019": 60.0,
      "runnerParty": "INC",
      "runnerVoteShare": 38.8,
      "electorate": 1510190,
      "turnout": 77.0,
      "category": "General"
    },
    {
      "name": "Baramati",
      "mp": "Supriya Sule",
      "party": "NCP (SP)",
      "voteShare": 50.8,
      "voteShare2019": 51.6,
      "runnerParty": "NCP",
      "runnerVoteShare": 42.0,
      "electorate": 1782549,
      "turnout": 64.9,
      "category": "General"
    },
    {
      "name": "Nagpur",
      "mp": "Nitin Gadkari",
      "party": "BJP",
      "voteShare": 46.4,
      "voteShare2019": 45.6,
      "runnerParty": "INC",
      "runnerVoteShare": 34.8,
      "electorate": 2190013,
      "turnout": 50.4,
      "category": "General"
    },
    {
      "name": "Pune",
      "mp": "Murlidhar Mohol",
      "party": "BJP",
      "voteShare": 47.6,
      "voteShare2019": 49.5,
      "runnerParty": "INC",
      "runnerVoteShare": 37.7,
      "electorate": 2379037,
      "turnout": 59.9,
      "category": "General"
    },
    {
      "name": "Kalyan",
      "mp": "Shrikant Shinde",
      "party": "SHS",
      "voteShare": 51.4,
      "voteShare2019": 48.0,
      "runnerParty": "SS (UBT)",
      "runnerVoteShare": 21.3,
      "electorate": 2017588,
      "turnout": 67.7,
      "category": "General"
    }
  ],
  "Manipur": [
    {
      "name": "Inner Manipur",
      "mp": "Angomcha Bimol Akoijam",
      "party": "INC",
      "voteShare": 51.1,
      "voteShare2019": 55.4,
      "runnerParty": "BJP",
      "runnerVoteShare": 43.6,
      "electorate": 1844908,
      "turnout": 78.3,
      "category": "General"
    },
    {
      "name": "Outer Manipur",
      "mp": "Alfred Kanngam Arthur",
      "party": "INC",
      "voteShare": 48.1,
      "voteShare2019": 46.0,
      "runnerParty": "NPF",
      "runnerVoteShare": 36.7,
      "electorate": 1843886,
      "turnout": 50.1,
      "category": "ST"
    },
    {
      "name": "Imphal",
      "mp": "Rajkumar Ranjan Singh",
      "party": "BJP",
      "voteShare": 42.4,
      "voteShare2019": 41.6,
      "runnerParty": "INC",
      "runnerVoteShare": 36.9,
      "electorate": 1600901,
      "turnout": 54.4,
      "category": "General"
    },
    {
      "name": "Thoubal",
      "mp": "Okram Ibobi Singh",
      "party": "INC",
      "voteShare": 49.4,
      "voteShare2019": 50.9,
      "runnerParty": "BJP",
      "runnerVoteShare": 42.2,
      "electorate": 2355223,
      "turnout": 76.4,
      "category": "General"
    },
    {
      "name": "Churachandpur",
      "mp": "Phungzathang Tonsing",
      "party": "INC",
      "voteShare": 44.1,
      "voteShare2019": 46.4,
      "runnerParty": "BJP",
      "runnerVoteShare": 37.3,
      "electorate": 1514953,
      "turnout": 56.3,
      "category": "ST"
    }
  ],
  "Meghalaya": [
    {
      "name": "Shillong",
      "mp": "Ricky A. J. Syngkon",
      "party": "VPP",
      "voteShare": 40.8,
      "voteShare2019": 42.1,
      "runnerParty": "INC",
      "runnerVoteShare": 22.4,
      "electorate": 1929596,
      "turnout": 59.8,
      "category": "ST"
    },
    {
      "name": "Tura",
      "mp": "Saleng A. Sangma",
      "party": "INC",
      "voteShare": 43.4,
      "voteShare2019": 38.9,
      "runnerParty": "NPP",
      "runnerVoteShare": 27.5,
      "electorate": 2433389,
      "turnout": 75.3,
      "category": "ST"
    },
    {
      "name": "Jowai",
      "mp": "Lapai",
      "party": "VPP",
      "voteShare": 42.1,
      "voteShare2019": 40.1,
      "runnerParty": "INC",
      "runnerVoteShare": 27.8,
      "electorate": 2299385,
      "turnout": 62.8,
      "category": "ST"
    },
    {
      "name": "Nongstoin",
      "mp": "K.P. Pangniang",
      "party": "HSPDP",
      "voteShare": 49.4,
      "voteShare2019": 52.0,
      "runnerParty": "INC",
      "runnerVoteShare": 37.7,
      "electorate": 1561882,
      "turnout": 50.5,
      "category": "ST"
    },
    {
      "name": "Williamnagar",
      "mp": "Marcuise Marak",
      "party": "NPP",
      "voteShare": 50.4,
      "voteShare2019": 47.5,
      "runnerParty": "INC",
      "runnerVoteShare": 25.9,
      "electorate": 2192399,
      "turnout": 52.1,
      "category": "ST"
    }
  ],
  "Mizoram": [
    {
      "name": "Mizoram",
      "mp": "Richard Vanlalhmangaiha",
      "party": "ZPM",
      "voteShare": 40.5,
      "voteShare2019": 43.5,
      "runnerParty": "MNF",
      "runnerVoteShare": 22.0,
      "electorate": 2255845,
      "turnout": 73.8,
      "category": "ST"
    },
    {
      "name": "Aizawl North",
      "mp": "Vanlalhlana",
      "party": "ZPM",
      "voteShare": 48.3,
      "voteShare2019": 48.4,
      "runnerParty": "MNF",
      "runnerVoteShare": 38.4,
      "electorate": 2258087,
      "turnout": 59.5,
      "category": "ST"
    },
    {
      "name": "Aizawl South",
      "mp": "K. Sapdanga",
      "party": "ZPM",
      "voteShare": 54.8,
      "voteShare2019": 57.6,
      "runnerParty": "MNF",
      "runnerVoteShare": 27.9,
      "electorate": 1782104,
      "turnout": 69.3,
      "category": "ST"
    },
    {
      "name": "Champhai",
      "mp": "T.J. Lalnuntluanga",
      "party": "MNF",
      "voteShare": 50.7,
      "voteShare2019": 47.4,
      "runnerParty": "ZPM",
      "runnerVoteShare": 39.6,
      "electorate": 1982160,
      "turnout": 76.9,
      "category": "ST"
    },
    {
      "name": "Lunglei",
      "mp": "Lalrinliana Sailo",
      "party": "MNF",
      "voteShare": 56.1,
      "voteShare2019": 58.2,
      "runnerParty": "ZPM",
      "runnerVoteShare": 45.6,
      "electorate": 2346574,
      "turnout": 77.2,
      "category": "ST"
    }
  ],
  "Nagaland": [
    {
      "name": "Nagaland",
      "mp": "S. Supongmeren Jamir",
      "party": "INC",
      "voteShare": 45.2,
      "voteShare2019": 48.4,
      "runnerParty": "NDPP",
      "runnerVoteShare": 25.4,
      "electorate": 1863772,
      "turnout": 62.9,
      "category": "General"
    },
    {
      "name": "Dimapur",
      "mp": "Toshitsungba Aier",
      "party": "NDPP",
      "voteShare": 49.3,
      "voteShare2019": 48.5,
      "runnerParty": "INC",
      "runnerVoteShare": 31.6,
      "electorate": 2473810,
      "turnout": 57.5,
      "category": "General"
    },
    {
      "name": "Kohima",
      "mp": "Kekhrie Yhome",
      "party": "NDPP",
      "voteShare": 48.8,
      "voteShare2019": 53.7,
      "runnerParty": "INC",
      "runnerVoteShare": 26.6,
      "electorate": 1619482,
      "turnout": 52.5,
      "category": "General"
    },
    {
      "name": "Mokokchung",
      "mp": "Metsubo Jamir",
      "party": "NDPP",
      "voteShare": 47.9,
      "voteShare2019": 52.7,
      "runnerParty": "INC",
      "runnerVoteShare": 37.5,
      "electorate": 2076484,
      "turnout": 65.2,
      "category": "General"
    },
    {
      "name": "Mon",
      "mp": "Noke Wangnao",
      "party": "NDPP",
      "voteShare": 56.4,
      "voteShare2019": 52.5,
      "runnerParty": "INC",
      "runnerVoteShare": 51.6,
      "electorate": 1767513,
      "turnout": 71.5,
      "category": "General"
    }
  ],
  "Odisha": [
    {
      "name": "Puri",
      "mp": "Sambit Patra",
      "party": "BJP",
      "voteShare": 40.3,
      "voteShare2019": 41.8,
      "runnerParty": "BJD",
      "runnerVoteShare": 30.5,
      "electorate": 1591169,
      "turnout": 50.3,
      "category": "General"
    },
    {
      "name": "Bhubaneswar",
      "mp": "Aparajita Sarangi",
      "party": "BJP",
      "voteShare": 47.5,
      "voteShare2019": 49.8,
      "runnerParty": "BJD",
      "runnerVoteShare": 43.5,
      "electorate": 1998295,
      "turnout": 60.6,
      "category": "General"
    },
    {
      "name": "Cuttack",
      "mp": "Bhartruhari Mahtab",
      "party": "BJP",
      "voteShare": 54.8,
      "voteShare2019": 51.7,
      "runnerParty": "BJD",
      "runnerVoteShare": 39.1,
      "electorate": 2095088,
      "turnout": 68.2,
      "category": "General"
    },
    {
      "name": "Kendrapara",
      "mp": "Baijayant Panda",
      "party": "BJP",
      "voteShare": 52.0,
      "voteShare2019": 49.6,
      "runnerParty": "BJD",
      "runnerVoteShare": 23.5,
      "electorate": 1713635,
      "turnout": 63.6,
      "category": "General"
    },
    {
      "name": "Sambalpur",
      "mp": "Dharmendra Pradhan",
      "party": "BJP",
      "voteShare": 49.3,
      "voteShare2019": 49.5,
      "runnerParty": "BJD",
      "runnerVoteShare": 22.9,
      "electorate": 2381456,
      "turnout": 63.5,
      "category": "General"
    }
  ],
  "Punjab": [
    {
      "name": "Amritsar",
      "mp": "Gurjeet Singh Aujla",
      "party": "INC",
      "voteShare": 59.7,
      "voteShare2019": 56.6,
      "runnerParty": "AAP",
      "runnerVoteShare": 23.6,
      "electorate": 2394028,
      "turnout": 60.5,
      "category": "General"
    },
    {
      "name": "Jalandhar",
      "mp": "Charanjit Singh Channi",
      "party": "INC",
      "voteShare": 48.0,
      "voteShare2019": 45.9,
      "runnerParty": "AAP",
      "runnerVoteShare": 42.0,
      "electorate": 1835914,
      "turnout": 59.6,
      "category": "SC"
    },
    {
      "name": "Ludhiana",
      "mp": "Amrinder Singh Raja Warring",
      "party": "INC",
      "voteShare": 54.8,
      "voteShare2019": 52.3,
      "runnerParty": "BJP",
      "runnerVoteShare": 28.7,
      "electorate": 1932605,
      "turnout": 64.3,
      "category": "General"
    },
    {
      "name": "Bathinda",
      "mp": "Harsimrat Kaur Badal",
      "party": "SAD",
      "voteShare": 59.9,
      "voteShare2019": 61.3,
      "runnerParty": "AAP",
      "runnerVoteShare": 27.8,
      "electorate": 1588014,
      "turnout": 79.1,
      "category": "General"
    },
    {
      "name": "Sangrur",
      "mp": "Gurmeet Singh Meet Hayer",
      "party": "AAP",
      "voteShare": 59.2,
      "voteShare2019": 55.1,
      "runnerParty": "INC",
      "runnerVoteShare": 34.7,
      "electorate": 1691005,
      "turnout": 70.0,
      "category": "General"
    }
  ],
  "Rajasthan": [
    {
      "name": "Kota",
      "mp": "Om Birla",
      "party": "BJP",
      "voteShare": 42.9,
      "voteShare2019": 46.9,
      "runnerParty": "INC",
      "runnerVoteShare": 32.7,
      "electorate": 1765223,
      "turnout": 52.1,
      "category": "General"
    },
    {
      "name": "Jodhpur",
      "mp": "Gajendra Singh Shekhawat",
      "party": "BJP",
      "voteShare": 58.4,
      "voteShare2019": 58.2,
      "runnerParty": "INC",
      "runnerVoteShare": 21.2,
      "electorate": 1906870,
      "turnout": 58.0,
      "category": "General"
    },
    {
      "name": "Barmer",
      "mp": "Ummeda Ram Beniwal",
      "party": "INC",
      "voteShare": 47.0,
      "voteShare2019": 42.2,
      "runnerParty": "IND",
      "runnerVoteShare": 24.4,
      "electorate": 1583216,
      "turnout": 64.7,
      "category": "General"
    },
    {
      "name": "Bikaner",
      "mp": "Arjun Ram Meghwal",
      "party": "BJP",
      "voteShare": 49.0,
      "voteShare2019": 45.1,
      "runnerParty": "INC",
      "runnerVoteShare": 35.3,
      "electorate": 2039391,
      "turnout": 69.6,
      "category": "SC"
    },
    {
      "name": "Jaipur",
      "mp": "Manju Sharma",
      "party": "BJP",
      "voteShare": 49.3,
      "voteShare2019": 53.0,
      "runnerParty": "INC",
      "runnerVoteShare": 38.1,
      "electorate": 2426973,
      "turnout": 72.8,
      "category": "General"
    }
  ],
  "Sikkim": [
    {
      "name": "Sikkim",
      "mp": "Indra Hang Subba",
      "party": "SKM",
      "voteShare": 48.8,
      "voteShare2019": 46.8,
      "runnerParty": "SDF",
      "runnerVoteShare": 20.9,
      "electorate": 1646034,
      "turnout": 66.5,
      "category": "General"
    },
    {
      "name": "Gangtok",
      "mp": "Pintso Namgyal Lepcha",
      "party": "SKM",
      "voteShare": 42.0,
      "voteShare2019": 45.1,
      "runnerParty": "SDF",
      "runnerVoteShare": 31.8,
      "electorate": 1790040,
      "turnout": 70.2,
      "category": "General"
    },
    {
      "name": "Namchi",
      "mp": "Krishna Kumari Rai",
      "party": "SKM",
      "voteShare": 49.6,
      "voteShare2019": 53.0,
      "runnerParty": "SDF",
      "runnerVoteShare": 45.3,
      "electorate": 2319332,
      "turnout": 68.7,
      "category": "General"
    },
    {
      "name": "Gyalshing",
      "mp": "Bhim Hang Limboo",
      "party": "SKM",
      "voteShare": 52.6,
      "voteShare2019": 49.4,
      "runnerParty": "SDF",
      "runnerVoteShare": 24.7,
      "electorate": 2434508,
      "turnout": 50.6,
      "category": "General"
    },
    {
      "name": "Mangan",
      "mp": "Samdup Lepcha",
      "party": "SKM",
      "voteShare": 42.3,
      "voteShare2019": 45.4,
      "runnerParty": "SDF",
      "runnerVoteShare": 34.5,
      "electorate": 2164796,
      "turnout": 77.4,
      "category": "General"
    }
  ],
  "Tamil Nadu": [
    {
      "name": "Chennai South",
      "mp": "Thamizhachi Thangapandian",
      "party": "DMK",
      "voteShare": 41.4,
      "voteShare2019": 39.0,
      "runnerParty": "BJP",
      "runnerVoteShare": 31.4,
      "electorate": 1719830,
      "turnout": 71.2,
      "category": "General"
    },
    {
      "name": "Coimbatore",
      "mp": "Ganapathy Rajkumar",
      "party": "DMK",
      "voteShare": 58.0,
      "voteShare2019": 62.6,
      "runnerParty": "BJP",
      "runnerVoteShare": 45.4,
      "electorate": 2168215,
      "turnout": 64.7,
      "category": "General"
    },
    {
      "name": "Madurai",
      "mp": "S. Venkatesan",
      "party": "CPI(M)",
      "voteShare": 44.1,
      "voteShare2019": 46.5,
      "runnerParty": "AIADMK",
      "runnerVoteShare": 30.2,
      "electorate": 2152789,
      "turnout": 77.7,
      "category": "General"
    },
    {
      "name": "Thoothukkudi",
      "mp": "Kanimozhi Karunanidhi",
      "party": "DMK",
      "voteShare": 47.3,
      "voteShare2019": 48.0,
      "runnerParty": "AIADMK",
      "runnerVoteShare": 36.0,
      "electorate": 2204518,
      "turnout": 54.6,
      "category": "General"
    },
    {
      "name": "Kanyakumari",
      "mp": "Vijay Vasanth",
      "party": "INC",
      "voteShare": 57.5,
      "voteShare2019": 60.1,
      "runnerParty": "BJP",
      "runnerVoteShare": 29.4,
      "electorate": 2094271,
      "turnout": 63.9,
      "category": "General"
    }
  ],
  "Telangana": [
    {
      "name": "Hyderabad",
      "mp": "Asaduddin Owaisi",
      "party": "AIMIM",
      "voteShare": 46.9,
      "voteShare2019": 48.8,
      "runnerParty": "BJP",
      "runnerVoteShare": 32.3,
      "electorate": 2108525,
      "turnout": 67.1,
      "category": "General"
    },
    {
      "name": "Secunderabad",
      "mp": "G. Kishan Reddy",
      "party": "BJP",
      "voteShare": 48.0,
      "voteShare2019": 51.5,
      "runnerParty": "INC",
      "runnerVoteShare": 40.0,
      "electorate": 2222336,
      "turnout": 79.2,
      "category": "General"
    },
    {
      "name": "Karimnagar",
      "mp": "Bandi Sanjay Kumar",
      "party": "BJP",
      "voteShare": 45.7,
      "voteShare2019": 42.7,
      "runnerParty": "INC",
      "runnerVoteShare": 43.4,
      "electorate": 2111204,
      "turnout": 77.5,
      "category": "General"
    },
    {
      "name": "Malkajgiri",
      "mp": "Eatala Rajender",
      "party": "BJP",
      "voteShare": 55.6,
      "voteShare2019": 54.4,
      "runnerParty": "INC",
      "runnerVoteShare": 47.7,
      "electorate": 1591954,
      "turnout": 70.1,
      "category": "General"
    },
    {
      "name": "Khammam",
      "mp": "Ramasayam Raghuram Reddy",
      "party": "INC",
      "voteShare": 47.9,
      "voteShare2019": 43.1,
      "runnerParty": "BRS",
      "runnerVoteShare": 26.1,
      "electorate": 2165669,
      "turnout": 71.4,
      "category": "General"
    }
  ],
  "Tripura": [
    {
      "name": "Tripura West",
      "mp": "Biplab Kumar Deb",
      "party": "BJP",
      "voteShare": 54.8,
      "voteShare2019": 58.9,
      "runnerParty": "INC",
      "runnerVoteShare": 47.7,
      "electorate": 2349620,
      "turnout": 52.9,
      "category": "General"
    },
    {
      "name": "Tripura East",
      "mp": "Kriti Devi Debbarman",
      "party": "BJP",
      "voteShare": 46.9,
      "voteShare2019": 46.6,
      "runnerParty": "CPI(M)",
      "runnerVoteShare": 26.0,
      "electorate": 2494677,
      "turnout": 67.6,
      "category": "ST"
    },
    {
      "name": "Agartala",
      "mp": "Sudip Roy Barman",
      "party": "INC",
      "voteShare": 55.4,
      "voteShare2019": 56.8,
      "runnerParty": "BJP",
      "runnerVoteShare": 25.3,
      "electorate": 2442632,
      "turnout": 59.2,
      "category": "General"
    },
    {
      "name": "Udaipur",
      "mp": "Pranajit Singha Roy",
      "party": "BJP",
      "voteShare": 56.6,
      "voteShare2019": 56.2,
      "runnerParty": "INC",
      "runnerVoteShare": 34.5,
      "electorate": 2401295,
      "turnout": 78.5,
      "category": "General"
    },
    {
      "name": "Dharmanagar",
      "mp": "Biswa Bandhu Sen",
      "party": "BJP",
      "voteShare": 56.1,
      "voteShare2019": 58.4,
      "runnerParty": "INC",
      "runnerVoteShare": 42.4,
      "electorate": 1579467,
      "turnout": 60.9,
      "category": "General"
    }
  ],
  "Uttar Pradesh": [
    {
      "name": "Varanasi",
      "mp": "Narendra Modi",
      "party": "BJP",
      "voteShare": 43.1,
      "voteShare2019": 47.9,
      "runnerParty": "INC",
      "runnerVoteShare": 30.0,
      "electorate": 2283423,
      "turnout": 65.0,
      "category": "General"
    },
    {
      "name": "Lucknow",
      "mp": "Rajnath Singh",
      "party": "BJP",
      "voteShare": 42.0,
      "voteShare2019": 42.4,
      "runnerParty": "SP",
      "runnerVoteShare": 36.7,
      "electorate": 2221188,
      "turnout": 79.4,
      "category": "General"
    },
    {
      "name": "Rae Bareli",
      "mp": "Rahul Gandhi",
      "party": "INC",
      "voteShare": 45.0,
      "voteShare2019": 40.4,
      "runnerParty": "BJP",
      "runnerVoteShare": 35.3,
      "electorate": 2257414,
      "turnout": 62.0,
      "category": "General"
    },
    {
      "name": "Kannauj",
      "mp": "Akhilesh Yadav",
      "party": "SP",
      "voteShare": 41.4,
      "voteShare2019": 36.9,
      "runnerParty": "BJP",
      "runnerVoteShare": 21.0,
      "electorate": 2125925,
      "turnout": 61.8,
      "category": "General"
    },
    {
      "name": "Amethi",
      "mp": "Kishori Lal Sharma",
      "party": "INC",
      "voteShare": 53.8,
      "voteShare2019": 55.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 46.4,
      "electorate": 2132897,
      "turnout": 77.0,
      "category": "General"
    }
  ],
  "Uttarakhand": [
    {
      "name": "Garhwal",
      "mp": "Anil Baluni",
      "party": "BJP",
      "voteShare": 57.0,
      "voteShare2019": 55.9,
      "runnerParty": "INC",
      "runnerVoteShare": 27.0,
      "electorate": 1618880,
      "turnout": 53.3,
      "category": "General"
    },
    {
      "name": "Haridwar",
      "mp": "Trivendra Singh Rawat",
      "party": "BJP",
      "voteShare": 40.2,
      "voteShare2019": 36.2,
      "runnerParty": "INC",
      "runnerVoteShare": 35.9,
      "electorate": 1757497,
      "turnout": 56.2,
      "category": "General"
    },
    {
      "name": "Almora",
      "mp": "Ajay Tamta",
      "party": "BJP",
      "voteShare": 53.3,
      "voteShare2019": 56.0,
      "runnerParty": "INC",
      "runnerVoteShare": 35.1,
      "electorate": 1638142,
      "turnout": 53.0,
      "category": "SC"
    },
    {
      "name": "Nainital",
      "mp": "Ajay Bhatt",
      "party": "BJP",
      "voteShare": 56.4,
      "voteShare2019": 60.4,
      "runnerParty": "INC",
      "runnerVoteShare": 26.1,
      "electorate": 2051499,
      "turnout": 61.5,
      "category": "General"
    },
    {
      "name": "Tehri Garhwal",
      "mp": "Mala Rajya Laxmi Shah",
      "party": "BJP",
      "voteShare": 40.6,
      "voteShare2019": 38.3,
      "runnerParty": "INC",
      "runnerVoteShare": 34.6,
      "electorate": 2324661,
      "turnout": 62.4,
      "category": "General"
    }
  ],
  "West Bengal": [
    {
      "name": "Diamond Harbour",
      "mp": "Abhishek Banerjee",
      "party": "TMC",
      "voteShare": 59.5,
      "voteShare2019": 58.0,
      "runnerParty": "BJP",
      "runnerVoteShare": 30.4,
      "electorate": 1904162,
      "turnout": 50.7,
      "category": "General"
    },
    {
      "name": "Krishnanagar",
      "mp": "Mahua Moitra",
      "party": "TMC",
      "voteShare": 47.9,
      "voteShare2019": 49.6,
      "runnerParty": "BJP",
      "runnerVoteShare": 43.8,
      "electorate": 1999352,
      "turnout": 76.0,
      "category": "General"
    },
    {
      "name": "Kolkata North",
      "mp": "Sudip Bandyopadhyay",
      "party": "TMC",
      "voteShare": 49.6,
      "voteShare2019": 47.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 44.1,
      "electorate": 1831891,
      "turnout": 63.4,
      "category": "General"
    },
    {
      "name": "Baharampur",
      "mp": "Yusuf Pathan",
      "party": "TMC",
      "voteShare": 41.9,
      "voteShare2019": 41.6,
      "runnerParty": "INC",
      "runnerVoteShare": 37.0,
      "electorate": 2292556,
      "turnout": 74.0,
      "category": "General"
    },
    {
      "name": "Asansol",
      "mp": "Shatrughan Sinha",
      "party": "TMC",
      "voteShare": 47.4,
      "voteShare2019": 47.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 31.4,
      "electorate": 2077989,
      "turnout": 79.2,
      "category": "General"
    }
  ],
  "Andaman and Nicobar Islands": [
    {
      "name": "Andaman and Nicobar",
      "mp": "Bishnu Pada Ray",
      "party": "BJP",
      "voteShare": 52.9,
      "voteShare2019": 50.4,
      "runnerParty": "INC",
      "runnerVoteShare": 26.9,
      "electorate": 2313961,
      "turnout": 59.9,
      "category": "General"
    },
    {
      "name": "Port Blair",
      "mp": "Kuldeep Rai Sharma",
      "party": "INC",
      "voteShare": 59.3,
      "voteShare2019": 57.1,
      "runnerParty": "BJP",
      "runnerVoteShare": 37.2,
      "electorate": 1649010,
      "turnout": 55.8,
      "category": "General"
    },
    {
      "name": "Nicobar",
      "mp": "Ajoy Bairagi",
      "party": "BJP",
      "voteShare": 43.8,
      "voteShare2019": 45.4,
      "runnerParty": "INC",
      "runnerVoteShare": 30.5,
      "electorate": 2414627,
      "turnout": 63.3,
      "category": "ST"
    },
    {
      "name": "Havelock",
      "mp": "Manoranjan Bhakta",
      "party": "INC",
      "voteShare": 43.5,
      "voteShare2019": 40.7,
      "runnerParty": "BJP",
      "runnerVoteShare": 41.0,
      "electorate": 1950691,
      "turnout": 55.1,
      "category": "General"
    },
    {
      "name": "Diglipur",
      "mp": "Vishal Jolly",
      "party": "BJP",
      "voteShare": 51.1,
      "voteShare2019": 49.8,
      "runnerParty": "INC",
      "runnerVoteShare": 42.0,
      "electorate": 2326185,
      "turnout": 75.9,
      "category": "General"
    }
  ],
  "Chandigarh": [
    {
      "name": "Chandigarh",
      "mp": "Manish Tewari",
      "party": "INC",
      "voteShare": 45.5,
      "voteShare2019": 45.8,
      "runnerParty": "BJP",
      "runnerVoteShare": 33.0,
      "electorate": 2255677,
      "turnout": 78.9,
      "category": "General"
    },
    {
      "name": "Manimajra",
      "mp": "Sanjay Tandon",
      "party": "BJP",
      "voteShare": 55.2,
      "voteShare2019": 56.3,
      "runnerParty": "INC",
      "runnerVoteShare": 47.8,
      "electorate": 2498550,
      "turnout": 56.0,
      "category": "General"
    },
    {
      "name": "Sector 17",
      "mp": "Kirron Kher",
      "party": "BJP",
      "voteShare": 53.8,
      "voteShare2019": 50.6,
      "runnerParty": "INC",
      "runnerVoteShare": 35.9,
      "electorate": 1785274,
      "turnout": 71.5,
      "category": "General"
    },
    {
      "name": "Sector 43",
      "mp": "Pawan Kumar Bansal",
      "party": "INC",
      "voteShare": 59.9,
      "voteShare2019": 64.6,
      "runnerParty": "BJP",
      "runnerVoteShare": 48.7,
      "electorate": 1727301,
      "turnout": 66.8,
      "category": "General"
    },
    {
      "name": "Sector 34",
      "mp": "Satya Pal Jain",
      "party": "BJP",
      "voteShare": 50.3,
      "voteShare2019": 52.0,
      "runnerParty": "INC",
      "runnerVoteShare": 29.4,
      "electorate": 2309775,
      "turnout": 60.5,
      "category": "General"
    }
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    {
      "name": "Dadra and Nagar Haveli",
      "mp": "Kalaben Delkar",
      "party": "BJP",
      "voteShare": 56.3,
      "voteShare2019": 59.1,
      "runnerParty": "INC",
      "runnerVoteShare": 41.4,
      "electorate": 1626511,
      "turnout": 70.8,
      "category": "ST"
    },
    {
      "name": "Daman and Diu",
      "mp": "Patel Umeshbhai Babubhai",
      "party": "IND",
      "voteShare": 55.6,
      "voteShare2019": 57.5,
      "runnerParty": "BJP",
      "runnerVoteShare": 24.0,
      "electorate": 2332989,
      "turnout": 54.6,
      "category": "General"
    },
    {
      "name": "Silvassa",
      "mp": "Mohan Delkar",
      "party": "IND",
      "voteShare": 47.4,
      "voteShare2019": 47.8,
      "runnerParty": "BJP",
      "runnerVoteShare": 37.6,
      "electorate": 2485150,
      "turnout": 63.1,
      "category": "General"
    },
    {
      "name": "Daman",
      "mp": "Lalu Patel",
      "party": "BJP",
      "voteShare": 54.9,
      "voteShare2019": 50.9,
      "runnerParty": "INC",
      "runnerVoteShare": 21.4,
      "electorate": 1693466,
      "turnout": 56.9,
      "category": "General"
    },
    {
      "name": "Diu",
      "mp": "Ketan Patel",
      "party": "INC",
      "voteShare": 55.1,
      "voteShare2019": 59.0,
      "runnerParty": "BJP",
      "runnerVoteShare": 27.8,
      "electorate": 1856151,
      "turnout": 66.6,
      "category": "General"
    }
  ],
  "Lakshadweep": [
    {
      "name": "Lakshadweep",
      "mp": "Muhammed Hamdulla Sayeed",
      "party": "INC",
      "voteShare": 54.1,
      "voteShare2019": 51.9,
      "runnerParty": "NCP (SP)",
      "runnerVoteShare": 44.0,
      "electorate": 1772085,
      "turnout": 65.3,
      "category": "ST"
    },
    {
      "name": "Kavaratti",
      "mp": "Mohammed Faizal P. P.",
      "party": "NCP (SP)",
      "voteShare": 58.8,
      "voteShare2019": 63.5,
      "runnerParty": "INC",
      "runnerVoteShare": 51.6,
      "electorate": 1927887,
      "turnout": 56.2,
      "category": "ST"
    },
    {
      "name": "Minicoy",
      "mp": "P. M. Sayeed",
      "party": "INC",
      "voteShare": 48.8,
      "voteShare2019": 50.5,
      "runnerParty": "NCP",
      "runnerVoteShare": 28.9,
      "electorate": 2100261,
      "turnout": 75.9,
      "category": "ST"
    },
    {
      "name": "Agatti",
      "mp": "Hamza",
      "party": "NCP",
      "voteShare": 40.2,
      "voteShare2019": 41.9,
      "runnerParty": "INC",
      "runnerVoteShare": 32.2,
      "electorate": 1665350,
      "turnout": 66.9,
      "category": "ST"
    },
    {
      "name": "Amini",
      "mp": "Cheriyakoya",
      "party": "INC",
      "voteShare": 51.0,
      "voteShare2019": 53.8,
      "runnerParty": "NCP",
      "runnerVoteShare": 30.2,
      "electorate": 1976045,
      "turnout": 53.1,
      "category": "ST"
    }
  ],
  "Delhi": [
    {
      "name": "New Delhi",
      "mp": "Bansuri Swaraj",
      "party": "BJP",
      "voteShare": 47.0,
      "voteShare2019": 50.1,
      "runnerParty": "AAP",
      "runnerVoteShare": 35.5,
      "electorate": 1886819,
      "turnout": 74.3,
      "category": "General"
    },
    {
      "name": "North East Delhi",
      "mp": "Manoj Tiwari",
      "party": "BJP",
      "voteShare": 58.1,
      "voteShare2019": 62.5,
      "runnerParty": "INC",
      "runnerVoteShare": 47.0,
      "electorate": 2311473,
      "turnout": 72.5,
      "category": "General"
    },
    {
      "name": "South Delhi",
      "mp": "Ramvir Singh Bidhuri",
      "party": "BJP",
      "voteShare": 41.6,
      "voteShare2019": 46.4,
      "runnerParty": "AAP",
      "runnerVoteShare": 32.0,
      "electorate": 2187884,
      "turnout": 77.7,
      "category": "General"
    },
    {
      "name": "East Delhi",
      "mp": "Harsh Malhotra",
      "party": "BJP",
      "voteShare": 49.6,
      "voteShare2019": 47.7,
      "runnerParty": "AAP",
      "runnerVoteShare": 21.3,
      "electorate": 2374412,
      "turnout": 55.5,
      "category": "General"
    },
    {
      "name": "Chandni Chowk",
      "mp": "Praveen Khandelwal",
      "party": "BJP",
      "voteShare": 41.7,
      "voteShare2019": 44.8,
      "runnerParty": "INC",
      "runnerVoteShare": 33.4,
      "electorate": 2320996,
      "turnout": 72.8,
      "category": "General"
    }
  ]
};